CREATE TABLE professores (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(120 CHAR) NOT NULL,
    email VARCHAR2(160 CHAR) NOT NULL UNIQUE
);

CREATE TABLE salas (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(30 CHAR) NOT NULL UNIQUE
);

CREATE TABLE equipamentos (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(120 CHAR) NOT NULL UNIQUE,
    tipo VARCHAR2(80 CHAR) NOT NULL,
    ativo NUMBER(1) NOT NULL
);

CREATE TABLE reservas (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id NUMBER(19) NOT NULL,
    curso VARCHAR2(120 CHAR) NOT NULL,
    sala_id NUMBER(19) NOT NULL,
    retirada TIMESTAMP NOT NULL,
    entrega TIMESTAMP NOT NULL,
    status VARCHAR2(20 CHAR) NOT NULL,
    CONSTRAINT fk_reserva_professor FOREIGN KEY (professor_id) REFERENCES professores(id),
    CONSTRAINT fk_reserva_sala FOREIGN KEY (sala_id) REFERENCES salas(id)
);

CREATE TABLE reserva_equipamento (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id NUMBER(19) NOT NULL,
    equipamento_id NUMBER(19) NOT NULL,
    quantidade NUMBER(10) NOT NULL,
    CONSTRAINT uk_reserva_equipamento UNIQUE (reserva_id, equipamento_id),
    CONSTRAINT fk_reserva_equipamento_reserva FOREIGN KEY (reserva_id) REFERENCES reservas(id),
    CONSTRAINT fk_reserva_equipamento_equipamento FOREIGN KEY (equipamento_id) REFERENCES equipamentos(id)
);
