spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=RESERVAS
spring.datasource.password=RESERVAS
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.h2.console.enabled=false
