CREATE TABLE professores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL UNIQUE
);

CREATE TABLE salas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE equipamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL UNIQUE,
    tipo VARCHAR(80) NOT NULL,
    ativo BOOLEAN NOT NULL
);

CREATE TABLE reservas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id BIGINT NOT NULL,
    curso VARCHAR(120) NOT NULL,
    sala_id BIGINT NOT NULL,
    retirada TIMESTAMP NOT NULL,
    entrega TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_reserva_professor FOREIGN KEY (professor_id) REFERENCES professores(id),
    CONSTRAINT fk_reserva_sala FOREIGN KEY (sala_id) REFERENCES salas(id)
);

CREATE TABLE reserva_equipamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id BIGINT NOT NULL,
    equipamento_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    CONSTRAINT uk_reserva_equipamento UNIQUE (reserva_id, equipamento_id),
    CONSTRAINT fk_reserva_equipamento_reserva FOREIGN KEY (reserva_id) REFERENCES reservas(id),
    CONSTRAINT fk_reserva_equipamento_equipamento FOREIGN KEY (equipamento_id) REFERENCES equipamentos(id)
);
